### ISSUE TITLE
Trips in OuterSpatial

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#7]
Are all of the trips in OuterSpatial already?

I need links to them or some other way to find them.

**Comment by ryanbranciforte** [comment]
Some, not all. I need to work on getting them all in there and getting the descriptions, photos, etc. set up. For now, I'll work to get one for Tahoe and one for Yose so you have something to work with.

**Comment by ryanbranciforte** [comment]
Here is a trip for Tahoe. I added photos
http://www.outerspatial.com/trips/1250/embed

Any reason we need to make an app for carless in OS? If so, we'd need to make two since the geographies are so distinct. 

Curious to see how the trips are integrated into OS. 

We need to be able to place and display the photos along a route. Ideally OS would allow the user to do that manually and via gps. I'll add a separate ticket in carless, but will apply to OS as well.

**Comment by jmoe** [comment]
Yeah, we could either make a apps or add attributes. Probably make apps.

**Comment by jmoe** [comment]
But then we would have to make orgs as well. Hmm.

**Comment by jmoe** [comment]
It's now possible to just add trips to the CarLess org in OuterSpatial

**Comment by jmoe** [comment]
How many trips are we shooting to have for launch?

**Comment by ryanbranciforte** [comment]
I'm starting to add trips. I'm shooting for 6 for each destination to start, sound about right? Currently we have 3 for Tahoe and 1 for Yosemite.

**Comment by ryanbranciforte** [comment]
update: we have 7 trip for south lake tahoe now. still only 1 for yosemite, but will add more early next week. 

here is the list of trips - https://docs.google.com/a/trailheadlabs.com/document/d/1ietw6I4PJFUINtkTC2CLTOvHAp1fam1lb7HRq8c_Nb0/edit?usp=sharing

i added all 7 to the carless site
i listed elevation for each trip in the google doc
3 of the 7 have photos
i set the 'feature image' for 3 of the trips
i am working on getting final copy and photos for each
